export enum ComponentType {
  PartMaster = 'PartMaster',
  PartMasterF2 = 'PartMasterF2',
  Profile = 'Profile',
  ChangeLocation = 'ChangeLocation',
  IncreaseInventory = 'IncreaseInventory',
  Inquiry = "Inquiry",
  SerialDocuments = "serialDocuments",
  ChangeSerial = "changeSerial",
  Reports = "reports",
  Mdat = "mdat",
  ER = "ER",
  Shipment = "shipment",
  Report2 = "report2",
  BulkTransfer = "bulkTransfer",
  DecreaseInventory = 'DecreaseInventory',
  Designer = 'Designer',
  Viewer = 'Viewer',
  ReportItemslist = 'ReportItemslist'
}
