import {NgModule} from "@angular/core";
import {
  DxAutocompleteModule,
  DxBoxModule,
  DxButtonGroupModule,
  DxButtonModule,
  DxCheckBoxModule,
  DxContextMenuModule,
  DxDataGridModule,
  DxDateBoxModule,
  DxFormModule,
  DxLinearGaugeModule,
  DxListModule,
  DxLookupModule,
  DxNumberBoxModule,
  DxRadioGroupModule,
  DxRangeSliderModule,
  DxResponsiveBoxModule,
  DxSelectBoxModule,
  DxSortableModule,
  DxTabPanelModule,
  DxTemplateModule,
  DxTextAreaModule,
  DxTextBoxModule
} from "devextreme-angular";

@NgModule({
  imports: [
    DxButtonModule,
    DxSortableModule,
    DxTabPanelModule,
    DxListModule,
    DxTemplateModule,
    DxDataGridModule,
    DxFormModule,
    DxContextMenuModule,
    DxCheckBoxModule,
    DxSelectBoxModule,
    DxNumberBoxModule,
    DxBoxModule,
    DxRadioGroupModule,
    DxTextAreaModule,
    DxResponsiveBoxModule,
    DxAutocompleteModule,
    DxLookupModule,
    DxButtonGroupModule,
    DxLinearGaugeModule,
    DxRangeSliderModule,
    DxTextBoxModule,
    DxDateBoxModule
  ],
  exports: [
    DxButtonModule,
    DxSortableModule,
    DxTabPanelModule,
    DxListModule,
    DxTemplateModule,
    DxDataGridModule,
    DxFormModule,
    DxContextMenuModule,
    DxCheckBoxModule,
    DxSelectBoxModule,
    DxNumberBoxModule,
    DxBoxModule,
    DxRadioGroupModule,
    DxTextAreaModule,
    DxResponsiveBoxModule,
    DxAutocompleteModule,
    DxLookupModule,
    DxButtonGroupModule,
    DxLinearGaugeModule,
    DxRangeSliderModule,
    DxTextBoxModule,
    DxDateBoxModule
  ]
})
export class DevExpressModule { }
